### ISSUE TITLE
Recode all current resources following this scheme

### ISSUE THREAD

**Issue by QuentinBrosse** [terraform-providers/terraform-provider-scaleway#143]
Rename all current resources following this scheme :
```
scaleway_{namespace}_{product}_{resource}
```

The old resources will be kept but deprecated. This will allow the creation of resources for our new products.

### Storage

- [x] `scaleway_bucket` → `scaleway_object_bucket` [#153, #150]

### Compute

- [x] `scaleway_server` → `scaleway_instance_server` [#165, #177, #174, #192, #186, #178, #193]
- [x] `scaleway_ip` → `scaleway_instance_ip` [#179, #178, #161]
- [x] `scaleway_ip_reverse_dns` → DEPRECATED (moved into `scaleway_instance_ip`) [#180]
- [x] `scaleway_security_group` → `scaleway_instance_security_group` [#181, #189]
- [x] `scaleway_security_group_rule` → DEPRECATED moved into `scaleway_instance_security_group`) [#182]
- [x] `scaleway_volume` → `scaleway_instance_volume` [#164, #176, #183, #186]
- [x] `scaleway_volume_attachment` → DEPRECATED (moved into `scaleway_instance_server`) [#185]
- [x] `scaleway_user_data` → DEPRECIATED (moved into `scaleway_instance_server`) [#184]
- [x] `scaleway_ssh_key` → `scaleway_account_ssh_key` [#148, #240]

### MISC

- [x] `scaleway_token` → DEPRECATED [#145]

**Comment by abitrolly** [comment]
This will make Terraform files more verbose. What kind of servers are expected to make sense of additional namespace information in `scaleway_compute_instance_server` ?

**Comment by QuentinBrosse** [comment]
Hi @abitrolly,

Our provider will support more products in the near future, that's why weed need to namespace our resources. Example of another type of server who will arrive soon: `scaleway_compute_baremetal_server`. :)

**Comment by abitrolly** [comment]
That makes sense, yes. ) Although I would leave it as `scaleway_baremetal` vs `scaleway_server` vs `scaleway_container` (for kubernetes).

**Comment by QuentinBrosse** [comment]
We prefer to be a bit more explicit with this consistent scheme: `scaleway_{category}_{productName}_{resourceName}`.

You are right, it's a bit more verbose but it has the advantage to don't leave room for ambiguity.

**Comment by abitrolly** [comment]
If Python puts readability first, because people read code more often than write, then for Terraform it is even more important, because you have to type resource names in command line quite often too. At least I had to type "aws_instance" a few times a month on my previous job. Now I will need to remember "scaleway_compute_instance_server", "scaleway_compute_instance" or whatever.. 

I think it is possible droping to "scaleway_compute_instance" and "scaleway_compute_baremetal", because "server" is to vague. DevOps could use more fine grained terminology already.

**Comment by QuentinBrosse** [comment]
@abitrolly we are in reflexion to remove the product category from the resource name. The `scaleway_{category}_{productName}_{resourceName}` scheme could became `scaleway_{productName}_{resourceName}.`.

It is not acted yet, but we are thinking about it.

**Comment by QuentinBrosse** [comment]
@abitrolly we will do it: `scaleway_{category}_{productName}_{resourceName}` scheme became `scaleway_{productName}_{resourceName}`.
